/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layer_Presentation;

import Layer_Business.RSA;


/**
 *
 * @author KGR
 */
public class JFDecryptEncryptRSA extends javax.swing.JFrame {

    /**
     * Creates new form JFDecryptEncryptRSA
     */
    public JFDecryptEncryptRSA() {
        initComponents();
    }

    
    public static void crypto() throws Exception
    {
        //Definimos un texto a cifrar
		String str = "Este es el texto a cifrar";
		
		System.out.println("\nTexto a cifrar:");
		System.out.println(str);
		
		//Instanciamos la clase
		RSA rsa = new RSA();
		
		//Generamos un par de claves
		//Admite claves de 512, 1024, 2048 y 4096 bits
		rsa.genKeyPair(512);
		
		
		String file_private = "/tmp/rsa.pri";
		String file_public = "/tmp/rsa.pub";
		
		//Las guardamos asi podemos usarlas despues
		//a lo largo del tiempo
		rsa.saveToDiskPrivateKey("/tmp/rsa.pri");
		rsa.saveToDiskPublicKey("/tmp/rsa.pub");
		
		//Ciframos y e imprimimos, el texto cifrado
		//es devuelto en la variable secure
		String secure = rsa.Encrypt(str);
		
		System.out.println("\nCifrado:");
		System.out.println(secure);
		
				
		
		//A modo de ejemplo creamos otra clase rsa
		RSA rsa2 = new RSA();
		
		//A diferencia de la anterior aca no creamos
		//un nuevo par de claves, sino que cargamos
		//el juego de claves que habiamos guadado
		rsa2.openFromDiskPrivateKey("/tmp/rsa.pri");	
		rsa2.openFromDiskPublicKey("/tmp/rsa.pub");
		
		//Le pasamos el texto cifrado (secure) y nos 
		//es devuelto el texto ya descifrado (unsecure) 
		String unsecure = rsa2.Decrypt(secure);
		
		//Imprimimos
		System.out.println("\nDescifrado:");
		System.out.println(unsecure);	
                
                /*
                Texto a cifrar:
                Este es el texto a cifrar

                Cifrado:
                19q1c3rn9p9rfnquycflpfqu0kv1rggv1wbtbvdkye2lwdi4lkoof2v3spgp768lbchd0g2qexl7t5csif8d8s5w574u79126pbz

                Descifrado:
                Este es el texto a cifrar
                */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDecryptEncryptRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDecryptEncryptRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDecryptEncryptRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDecryptEncryptRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDecryptEncryptRSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
